### ISSUE TITLE
Affichage produit front-office : améliorer l'affichage quand un produit n'est pas disponible

### ISSUE THREAD

**Issue by Cylecq** [WildCodeSchool/2023-03-wns-keller-groupe4#35]
- Améliorer dans la page "ProductsListPage"
- Améliorer dans la page ''ProductDetails"

## ProductDetails
![Screenshot 2023-08-31 at 12 21 28](https://github.com/WildCodeSchool/2023-03-wns-keller-groupe4/assets/108573955/07b0514b-0d7f-41a6-9575-7d63bdf77d66)

## ProductsListPage
![Screenshot 2023-08-31 at 12 21 39](https://github.com/WildCodeSchool/2023-03-wns-keller-groupe4/assets/108573955/44f9cdb3-cc0a-44cd-a3ce-3c8ba5a7afe3)

**Comment by valquino** [comment]
Fixé dans la PR#69
![img](https://github.com/WildCodeSchool/2023-03-wns-keller-groupe4/assets/100536963/6f910895-0380-4623-962e-28f5b22bd7a6)
