### ISSUE TITLE
Affichage produit : enlever "BRAND NAME"

### ISSUE THREAD

**Issue by Cylecq** [WildCodeSchool/2023-03-wns-keller-groupe4#36]
Dans l'afficahge produit dans le front et le back-office, il faudrait enlever BRAND NAME. À aucun moment on a le détail de la marque dans la BDD

![Screenshot 2023-08-31 at 12 33 21](https://github.com/WildCodeSchool/2023-03-wns-keller-groupe4/assets/108573955/c607a3c8-30ff-4876-81ae-c724d8565347)

**Comment by valquino** [comment]
yep, enlever review aussi du coup mais ça deviendrait vide. En revanche on a le champs description qui n'est pas utilisé ici. Ne mettrait-on pas un Lorem Ipsum?

**Comment by valquino** [comment]
Résolu par PR#70

![img](https://github.com/WildCodeSchool/2023-03-wns-keller-groupe4/assets/100536963/17cc7440-f29d-40dc-b301-04f2f9ece3b6)
